"""Generate user-facing schema documentation from the stable output contract."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .crop_profiles import CROP_PROFILES
from .schema import (
    IDENTITY_COLUMNS,
    MONTHLY_FEATURE_COLUMNS,
    OPTIONAL_CLIMATE_CONTEXT_COLUMNS,
    QUALITY_COLUMNS,
    STATIC_FEATURE_COLUMNS,
)


_DESCRIPTIONS = {
    "sample_id": "Stable `grid_id__YYYY-MM` row identifier.",
    "grid_id": "5 km equal-area Myanmar grid-cell identifier generated by the GEE exporter.",
    "year_month": "Observation month in YYYY-MM format.",
    "longitude": "Grid-cell centroid longitude in EPSG:4326 degrees.",
    "latitude": "Grid-cell centroid latitude in EPSG:4326 degrees.",
    "admin0_name": "Country name from GAUL context, expected to be Myanmar.",
    "admin1_name": "Optional first-level administrative name; null if not joined.",
    "admin2_name": "Optional second-level administrative name; null if not joined.",
    "spatial_block_id": "0.5-degree spatial CV block; use split manifest for folds.",
    "elevation_m": "SRTM elevation in metres.",
    "slope_degrees": "Terrain slope in degrees.",
    "aspect_degrees": "Terrain aspect in degrees clockwise from north.",
    "surface_water_occurrence_pct": "JRC Global Surface Water occurrence percentage; static water-access proxy.",
    "distance_to_surface_water_m": "Approximate distance to mapped surface water in metres; proxy, not irrigation infrastructure.",
    "soil_ph_h2o_0_30cm": "Thickness-weighted SoilGrids 0–30 cm pH in water.",
    "soil_sand_pct_0_30cm": "Thickness-weighted SoilGrids 0–30 cm sand percentage.",
    "soil_silt_pct_0_30cm": "Thickness-weighted SoilGrids 0–30 cm silt percentage.",
    "soil_clay_pct_0_30cm": "Thickness-weighted SoilGrids 0–30 cm clay percentage.",
    "soil_soc_g_kg_0_30cm": "Thickness-weighted SoilGrids 0–30 cm organic-carbon concentration in g/kg.",
    "soil_cec_cmol_kg_0_30cm": "Thickness-weighted SoilGrids 0–30 cm CEC in cmol(c)/kg.",
    "soil_ph_h2o_uncertainty_pct": "Approximate thickness-weighted SoilGrids relative pH uncertainty; null for mean-only GEE assets.",
    "ndvi_median": "Cloud-masked Sentinel-2 monthly median NDVI.",
    "ndwi_mcf_median": "Cloud-masked Sentinel-2 McFeeters NDWI monthly median; surface/canopy water proxy, not soil moisture.",
    "ndmi_median": "Cloud-masked Sentinel-2 NDMI monthly median; canopy/surface-moisture proxy, not soil moisture.",
    "s2_scene_count": "Number of Sentinel-2 source scenes available for the month before cloud masking.",
    "s2_valid_observation_count": "Number of valid Sentinel-2 images contributing to the month.",
    "s2_cloudy_pixel_fraction": "Fraction of source Sentinel-2 observations flagged cloudy before compositing.",
    "s1_vv_db_median": "Sentinel-1 monthly median VV backscatter in dB.",
    "s1_vh_db_median": "Sentinel-1 monthly median VH backscatter in dB.",
    "s1_scene_count": "Number of Sentinel-1 source scenes contributing to the monthly radar features.",
    "chirps_precipitation_mm": "CHIRPS daily precipitation summed over the calendar month, mm.",
    "monthly_rainfall_mm": "Canonical alias of monthly CHIRPS precipitation, mm.",
    "annual_rainfall_mm": "Trailing 12-month CHIRPS precipitation total, mm.",
    "mean_temperature_c": "ERA5-Land monthly mean 2 m air temperature, °C.",
    "min_temperature_c": "ERA5-Land monthly minimum 2 m air temperature, °C.",
    "max_temperature_c": "ERA5-Land monthly maximum 2 m air temperature, °C.",
    "solar_radiation_mj_m2_day": "ERA5-Land mean daily downward surface solar radiation, MJ m⁻² day⁻¹.",
    "era5_soil_moisture_m3_m3": "ERA5-Land layer-1 volumetric soil-water content, m³/m³.",
    "rainfall_normal_1991_2020_mm": "CHIRPS v3 mean rainfall for the same calendar month over the fixed 1991–2020 normal period, mm.",
    "rainfall_anomaly_1991_2020_mm": "Target-month CHIRPS v3 rainfall minus the 1991–2020 same-month normal, mm.",
    "rainfall_anomaly_1991_2020_pct": "Target-month CHIRPS v3 rainfall anomaly as a percentage of the 1991–2020 same-month normal.",
    "temperature_normal_1991_2020_c": "ERA5-Land mean 2 m air temperature for the same calendar month over 1991–2020, °C.",
    "temperature_anomaly_1991_2020_c": "Target-month ERA5-Land mean temperature minus the 1991–2020 same-month normal, °C.",
    "water_availability_score": "0–100 transparent proxy derived from physical soil water, annual rain, water occurrence and water distance; not a direct irrigation measurement.",
    "s2_data_status": "Availability/quality flag; never infer data from a missing optical month.",
    "s1_data_status": "Availability flag for optional Sentinel-1 support features.",
    "rainfall_data_status": "Whether final rainfall came from a complete local CHIRPS v3 cache or an explicitly allowed GEE staging fallback.",
    "soil_data_status": "Soil source/fallback and completeness flag.",
    "feature_missing_fraction": "Fraction of model feature fields that are null in the row.",
    "usable_for_training": "True only when the row's feature_missing_fraction is at or below the configured release threshold; false rows are retained for coverage auditing but must be excluded from model fitting.",
    "source_versions_json": "Compact source collection identifiers; see source manifest for full provenance.",
    "processing_timestamp_utc": "UTC timestamp at final assembly.",
}


def write_data_dictionary(path: str | Path, crops: Iterable[str]) -> Path:
    """Write a Markdown dictionary for the primary table and label policy."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Myanmar agricultural Geo-CSV data dictionary",
        "",
        "One row represents a 5 km Myanmar grid-cell centroid for one calendar month. Values remain in physical units; normalisation belongs inside a leakage-safe training split.",
        "",
        "## Feature columns",
        "",
        "| Column | Meaning |",
        "| --- | --- |",
    ]
    for column in IDENTITY_COLUMNS + STATIC_FEATURE_COLUMNS + MONTHLY_FEATURE_COLUMNS + QUALITY_COLUMNS:
        lines.append(f"| `{column}` | {_DESCRIPTIONS.get(column, 'See source manifest.')} |")
    lines.extend(
        [
            "",
            "## Optional historical climate-context columns",
            "",
            "These columns are present only in releases that explicitly enable the 1991–2020 climate-context contract. They describe historical normals and anomalies; they are not forecasts, future climate scenarios, or causal climate-change attribution.",
            "",
            "| Column | Meaning |",
            "| --- | --- |",
        ]
    )
    for column in OPTIONAL_CLIMATE_CONTEXT_COLUMNS:
        lines.append(
            f"| `{column}` | {_DESCRIPTIONS.get(column, 'See source manifest.')} |"
        )
    lines.extend(["", "## Suitability label columns", "", "| Pattern | Meaning |", "| --- | --- |"])
    lines.extend(
        [
            "| `suitability_score__{crop}` | Provisional 0–100 agronomic rule score, optionally calibrated by a supplied observed label. It is not ground truth. |",
            "| `is_suitable__{crop}` | Boolean score threshold (default ≥70); null when required environmental feature coverage is insufficient. |",
            "| `label_source__{crop}` | `rule_based`, `hybrid_rule_observed`, or `observed`. |",
            "| `label_confidence__{crop}` | Transparent confidence, deliberately capped at the configured rules-only limit (default 0.45; never above 0.50). |",
            "",
            "## Target crops and profile caveat",
            "",
        ]
    )
    for crop in crops:
        profile = CROP_PROFILES.get(crop)
        if profile:
            lines.append(f"- `{crop}` — {profile.display_name}: {profile.notes}")
        else:
            lines.append(f"- `{crop}` — configured crop without a bundled profile.")
    lines.extend(
        [
            "",
            "## Important interpretation limits",
            "",
            "- NDWI and NDMI are optical canopy/surface-moisture proxies, not physical soil-moisture observations.",
            "- Water availability is a screening proxy; confirm irrigation rights, drainage, flood risk, land tenure, local varieties, pests and market conditions before recommending a crop.",
            "- SoilGrids values are modeled estimates with spatial uncertainty. Local laboratory sampling supersedes them when available.",
            "",
        ]
    )
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination
